import React from "react";
import "../globals.css";
import clsx from "clsx";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import navItems from "@/src/data/navItems.json";
import Footer from "@/components/feature/layout/footer/footer";
import { FloatingNav } from "@/components/ui/floating-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Munna's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={clsx(inter.className, "bg-background h-full")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <FloatingNav appName="X Y" navItems={navItems} className="" />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
